// Generated by scripts/generatePersonToSong.ts -- do not hand-edit.
// Committed, one-time, cross-grid assignment (docs/grid-content-pipeline.md §4).
// Rerun with --force only if you deliberately want a new assignment.
import type { Person } from "./people";

export const personToSong: Record<Person, string> = {
  "Sarah": "Song E",
  "Jason": "Song C",
  "James": "Song F",
  "Ben": "Song B",
  "Maria": "Song D",
  "Ciara": "Song A",
  "Thomas": "Song E"
};
