// Generated by scripts/generatePersonToSong.ts -- do not hand-edit.
// Committed, one-time, cross-grid assignment (docs/grid-content-pipeline.md §4).
// Rerun with --force only if you deliberately want a new assignment.
import type { Person } from "./people";

export const personToSong: Record<Person, string> = {
  "Ciara": "September",
  "Thomas": "Conga",
  "James": "Everybody Wants to Rule the World",
  "Jason": "One Way or Another",
  "Ben": "Disco Inferno",
  "Sarah": "I Ran (So Far Away)",
  "Maria": "September"
};
