import fs from "fs/promises";
import path from "path";
import { people } from "../people";
import { songs } from "../songs";

// One-time, manually-run script: randomly assigns each of the 7 people a
// song from the 6-song list via cyclic assignment on two independent random
// permutations, so exactly one song is shared by two people and the other
// five are assigned to exactly one person each -- surjective and unbiased
// (docs/grid-content-pipeline.md §4). Writes a committed personToSong.ts.
// NOT regenerated by any later grid-generation attempt -- makeGrid has no
// cross-grid awareness at all, this table is just a fixed input to it.
//
// Usage: npx tsx data/disney-2026/scripts/generatePersonToSong.ts [--force]

function shuffle<T>(arr: readonly T[]): T[] {
  return [...arr]
    .map((item) => ({ item, sort: Math.random() }))
    .sort((a, b) => a.sort - b.sort)
    .map(({ item }) => item);
}

const outputPath = path.join("data", "disney-2026", "personToSong.ts");
const force = process.argv.includes("--force");

const exists = await fs
  .access(outputPath)
  .then(() => true)
  .catch(() => false);
if (exists && !force) {
  console.error(
    `${outputPath} already exists -- pass --force to overwrite the committed assignment.`
  );
  process.exit(1);
}

if (people.length !== songs.length + 1) {
  throw new Error(
    `Cyclic assignment needs exactly one more person than songs -- got ${people.length} people, ${songs.length} songs.`
  );
}

const shuffledPeople = shuffle(people);
const shuffledSongs = shuffle(songs);

const personToSong: Record<string, string> = {};
shuffledPeople.forEach((person, i) => {
  personToSong[person] = shuffledSongs[i % shuffledSongs.length];
});

const contents =
  `// Generated by scripts/generatePersonToSong.ts -- do not hand-edit.\n` +
  `// Committed, one-time, cross-grid assignment (docs/grid-content-pipeline.md §4).\n` +
  `// Rerun with --force only if you deliberately want a new assignment.\n` +
  `import type { Person } from "./people";\n\n` +
  `export const personToSong: Record<Person, string> = ${JSON.stringify(personToSong, null, 2)};\n`;

await fs.writeFile(outputPath, contents);
console.log(`Wrote ${outputPath}:`);
console.log(personToSong);
