import fs from "fs/promises";
import path from "path";
import { people } from "../people";
import { songs } from "../songs";
import { assignSongs } from "../assignSongs";

// One-time, manually-run script: randomly assigns each of the 7 people a
// song from the 6-song list (see ../assignSongs.ts for the algorithm and
// docs/grid-content-pipeline.md §4 for why it's unbiased). Writes a
// committed personToSong.ts. NOT regenerated by any later grid-generation
// attempt -- makeGrid has no cross-grid awareness at all, this table is
// just a fixed input to it.
//
// Usage: npx tsx data/disney-2026/scripts/generatePersonToSong.ts [--force]

const outputPath = path.join("data", "disney-2026", "personToSong.ts");
const force = process.argv.includes("--force");

const exists = await fs
  .access(outputPath)
  .then(() => true)
  .catch(() => false);
if (exists && !force) {
  console.error(
    `${outputPath} already exists -- pass --force to overwrite the committed assignment.`
  );
  process.exit(1);
}

const personToSong = assignSongs(people, songs);

const contents =
  `// Generated by scripts/generatePersonToSong.ts -- do not hand-edit.\n` +
  `// Committed, one-time, cross-grid assignment (docs/grid-content-pipeline.md §4).\n` +
  `// Rerun with --force only if you deliberately want a new assignment.\n` +
  `import type { Person } from "./people";\n\n` +
  `export const personToSong: Record<Person, string> = ${JSON.stringify(personToSong, null, 2)};\n`;

await fs.writeFile(outputPath, contents);
console.log(`Wrote ${outputPath}:`);
console.log(personToSong);
